server:
  port: 8181

spring:
  application:
    name: "PayServise"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hikari
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    open-in-view: false
  flyway:
    detectEncoding: true
    encoding: ISO_8859_1

service:
  name: Gleb
  family: Shishkin

integrations:
  executors:
    payments-executor-client:
      url: "http://localhost:8080"
      connect-timeout: 1s
      read-timeout: 30s


